#!/usr/bin/env python3
"""Generate the TypeScript built-in ruleset module from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULESETS_DIR = ROOT / "rulesets"
OUTPUT = ROOT / "packages" / "hushspec" / "src" / "builtin.ts"

BUILTIN_NAMES = [
    "default",
    "strict",
    "permissive",
    "ai-agent",
    "cicd",
    "remote-desktop",
]


def render() -> str:
    lines = [
        "// Code generated by scripts/generate_ts_builtins.py. DO NOT EDIT.",
        "",
        "import YAML from 'yaml';",
        "import type { HushSpec } from './schema.js';",
        "",
        "export const BUILTIN_NAMES = [",
    ]

    for name in BUILTIN_NAMES:
        lines.append(f"  {json.dumps(name)},")

    lines.extend(
        [
            "] as const;",
            "",
            "export type BuiltinName = (typeof BUILTIN_NAMES)[number];",
            "",
            "const BUILTIN_RULESETS: Record<BuiltinName, string> = {",
        ]
    )

    for name in BUILTIN_NAMES:
        yaml_content = (RULESETS_DIR / f"{name}.yaml").read_text()
        lines.append(f"  {json.dumps(name)}: {json.dumps(yaml_content)},")

    lines.extend(
        [
            "};",
            "",
            "/**",
            " * Parsed directly with YAML.parse (no regex validation) because builtins",
            " * may contain RE2/PCRE patterns like `(?i)` that aren't valid JS regex.",
            " */",
            "export function loadBuiltin(name: string): HushSpec | null {",
            "  const resolved = name.startsWith('builtin:') ? name.slice(8) : name;",
            "",
            "  if (!(BUILTIN_NAMES as readonly string[]).includes(resolved)) {",
            "    return null;",
            "  }",
            "",
            "  const yaml = BUILTIN_RULESETS[resolved as BuiltinName];",
            "  const doc = YAML.parse(yaml) as HushSpec;",
            "  if (!doc || typeof doc !== 'object' || !doc.hushspec) {",
            "    return null;",
            "  }",
            "  return doc;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if builtin.ts is out of date")
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
