use clap::ValueEnum;
use colored::Colorize;
use std::path::PathBuf;

#[derive(clap::Args)]
pub struct InitArgs {
    /// Security preset
    #[arg(long, default_value = "default")]
    preset: Preset,

    /// Directory to create .hushspec/ in
    #[arg(long, default_value = ".")]
    dir: PathBuf,
}

#[derive(Clone, Copy, ValueEnum)]
enum Preset {
    Permissive,
    Default,
    Strict,
}

pub fn run(args: InitArgs) -> i32 {
    let base = args.dir.join(".hushspec");

    if base.exists() {
        eprintln!("{} {} already exists", "ERROR".red(), base.display());
        return 1;
    }

    let tests_dir = base.join("tests");
    if let Err(e) = std::fs::create_dir_all(&tests_dir) {
        eprintln!("{} Failed to create directory: {e}", "ERROR".red());
        return 1;
    }

    let policy = match args.preset {
        Preset::Permissive => PERMISSIVE_POLICY,
        Preset::Default => DEFAULT_POLICY,
        Preset::Strict => STRICT_POLICY,
    };

    let policy_path = base.join("policy.yaml");
    if let Err(e) = std::fs::write(&policy_path, policy) {
        eprintln!("{} Failed to write policy: {e}", "ERROR".red());
        return 1;
    }

    let test_content = starter_test(args.preset);
    let test_path = tests_dir.join("policy.test.yaml");
    if let Err(e) = std::fs::write(&test_path, test_content) {
        eprintln!("{} Failed to write test file: {e}", "ERROR".red());
        return 1;
    }

    let preset_name = match args.preset {
        Preset::Permissive => "permissive",
        Preset::Default => "default",
        Preset::Strict => "strict",
    };

    println!(
        "  {} {} (from {} preset)",
        "Created".green().bold(),
        policy_path.display(),
        preset_name,
    );
    println!(
        "  {} {} (3 starter cases)",
        "Created".green().bold(),
        test_path.display(),
    );

    println!();
    println!("{}", "Next steps:".bold());
    println!(
        "  1. Review your policy:      {}",
        format!("cat {}", policy_path.display()).dimmed()
    );
    println!(
        "  2. Validate it:             {}",
        format!("hushspec validate {}", policy_path.display()).dimmed()
    );
    println!(
        "  3. Run tests:               {}",
        format!("hushspec test --fixtures {}", tests_dir.display()).dimmed()
    );

    0
}

fn starter_test(preset: Preset) -> &'static str {
    match preset {
        Preset::Permissive => PERMISSIVE_TEST,
        Preset::Default => DEFAULT_TEST,
        Preset::Strict => STRICT_TEST,
    }
}

const DEFAULT_POLICY: &str = r#"# HushSpec Policy
# Generated by: hushspec init --preset default
hushspec: "0.1.0"
name: my-policy
description: Default security rules for AI agent execution

rules:
  forbidden_paths:
    patterns:
      - "**/.ssh/**"
      - "**/.aws/**"
      - "**/.env"
      - "**/.env.*"
    exceptions: []

  egress:
    allow:
      - "api.github.com"
      - "github.com"
      - "*.npmjs.org"
      - "registry.npmjs.org"
      - "pypi.org"
    block: []
    default: block

  tool_access:
    allow: []
    block:
      - shell_exec
      - run_command
    require_confirmation:
      - file_write
      - file_delete
    default: allow
"#;

const PERMISSIVE_POLICY: &str = r#"# HushSpec Policy
# Generated by: hushspec init --preset permissive
hushspec: "0.1.0"
name: my-policy
description: Permissive security rules for development

rules:
  egress:
    allow:
      - "*"
    block: []
    default: allow

  tool_access:
    allow: []
    block: []
    require_confirmation: []
    default: allow
"#;

const STRICT_POLICY: &str = r#"# HushSpec Policy
# Generated by: hushspec init --preset strict
hushspec: "0.1.0"
name: my-policy
description: Strict security rules with minimal permissions

rules:
  forbidden_paths:
    patterns:
      - "**/.ssh/**"
      - "**/.aws/**"
      - "**/.env"
      - "**/.env.*"
      - "**/.gnupg/**"
      - "**/.kube/**"
      - "**/.docker/**"
      - "/etc/shadow"
      - "/etc/passwd"
    exceptions: []

  egress:
    allow: []
    block: []
    default: block

  secret_patterns:
    patterns:
      - name: aws_access_key
        pattern: "AKIA[0-9A-Z]{16}"
        severity: critical
      - name: private_key
        pattern: "-----BEGIN\\s+(RSA\\s+)?PRIVATE\\s+KEY-----"
        severity: critical
    skip_paths:
      - "**/test/**"
      - "**/tests/**"

  tool_access:
    allow:
      - read_file
      - list_directory
      - search
    block: []
    require_confirmation: []
    default: block
"#;

const DEFAULT_TEST: &str = r#"hushspec_test: "0.1.0"
description: "Starter tests for default policy"
policy:
  hushspec: "0.1.0"
  rules:
    egress:
      allow:
        - "api.github.com"
        - "github.com"
        - "*.npmjs.org"
        - "registry.npmjs.org"
        - "pypi.org"
      block: []
      default: block
    tool_access:
      allow: []
      block:
        - shell_exec
        - run_command
      require_confirmation:
        - file_write
        - file_delete
      default: allow
cases:
  - description: "allow egress to github"
    action:
      type: egress
      target: "api.github.com"
    expect:
      decision: allow
      matched_rule: rules.egress.allow
  - description: "deny egress to unknown domain"
    action:
      type: egress
      target: "evil.example.com"
    expect:
      decision: deny
      matched_rule: rules.egress.default
  - description: "block shell_exec tool"
    action:
      type: tool_call
      target: "shell_exec"
    expect:
      decision: deny
      matched_rule: rules.tool_access.block
"#;

const PERMISSIVE_TEST: &str = r#"hushspec_test: "0.1.0"
description: "Starter tests for permissive policy"
policy:
  hushspec: "0.1.0"
  rules:
    egress:
      allow:
        - "*"
      block: []
      default: allow
    tool_access:
      allow: []
      block: []
      require_confirmation: []
      default: allow
cases:
  - description: "allow egress to any domain"
    action:
      type: egress
      target: "anything.example.com"
    expect:
      decision: allow
      matched_rule: rules.egress.allow
  - description: "allow any tool call"
    action:
      type: tool_call
      target: "any_tool"
    expect:
      decision: allow
      matched_rule: rules.tool_access.default
  - description: "allow file read"
    action:
      type: file_read
      target: "/some/path.txt"
    expect:
      decision: allow
"#;

const STRICT_TEST: &str = r#"hushspec_test: "0.1.0"
description: "Starter tests for strict policy"
policy:
  hushspec: "0.1.0"
  rules:
    egress:
      allow: []
      block: []
      default: block
    tool_access:
      allow:
        - read_file
        - list_directory
        - search
      block: []
      require_confirmation: []
      default: block
cases:
  - description: "deny all egress by default"
    action:
      type: egress
      target: "api.github.com"
    expect:
      decision: deny
      matched_rule: rules.egress.default
  - description: "allow read_file tool"
    action:
      type: tool_call
      target: "read_file"
    expect:
      decision: allow
      matched_rule: rules.tool_access.allow
  - description: "block unknown tool"
    action:
      type: tool_call
      target: "dangerous_tool"
    expect:
      decision: deny
      matched_rule: rules.tool_access.default
"#;
