// Code generated by scripts/generate_sdk_models.py. DO NOT EDIT.

package hushspec

type MergeStrategy string

const (
	MergeStrategyReplace   MergeStrategy = "replace"
	MergeStrategyMerge     MergeStrategy = "merge"
	MergeStrategyDeepMerge MergeStrategy = "deep_merge"
)

type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityError    Severity = "error"
	SeverityWarn     Severity = "warn"
)

type DefaultAction string

const (
	DefaultActionAllow DefaultAction = "allow"
	DefaultActionBlock DefaultAction = "block"
)

type ComputerUseMode string

const (
	ComputerUseModeObserve    ComputerUseMode = "observe"
	ComputerUseModeGuardrail  ComputerUseMode = "guardrail"
	ComputerUseModeFailClosed ComputerUseMode = "fail_closed"
)

type TransitionTrigger string

const (
	TransitionTriggerUserApproval      TransitionTrigger = "user_approval"
	TransitionTriggerUserDenial        TransitionTrigger = "user_denial"
	TransitionTriggerCriticalViolation TransitionTrigger = "critical_violation"
	TransitionTriggerAnyViolation      TransitionTrigger = "any_violation"
	TransitionTriggerTimeout           TransitionTrigger = "timeout"
	TransitionTriggerBudgetExhausted   TransitionTrigger = "budget_exhausted"
	TransitionTriggerPatternMatch      TransitionTrigger = "pattern_match"
)

type OriginDefaultBehavior string

const (
	OriginDefaultBehaviorDeny           OriginDefaultBehavior = "deny"
	OriginDefaultBehaviorMinimalProfile OriginDefaultBehavior = "minimal_profile"
)

type DetectionLevel string

const (
	DetectionLevelSafe       DetectionLevel = "safe"
	DetectionLevelSuspicious DetectionLevel = "suspicious"
	DetectionLevelHigh       DetectionLevel = "high"
	DetectionLevelCritical   DetectionLevel = "critical"
)

type Classification string

const (
	ClassificationPublic       Classification = "public"
	ClassificationInternal     Classification = "internal"
	ClassificationConfidential Classification = "confidential"
	ClassificationRestricted   Classification = "restricted"
)

type LifecycleState string

const (
	LifecycleStateDraft      LifecycleState = "draft"
	LifecycleStateReview     LifecycleState = "review"
	LifecycleStateApproved   LifecycleState = "approved"
	LifecycleStateDeployed   LifecycleState = "deployed"
	LifecycleStateDeprecated LifecycleState = "deprecated"
	LifecycleStateArchived   LifecycleState = "archived"
)

type HushSpec struct {
	HushSpecVersion string              `yaml:"hushspec" json:"hushspec"`
	Name            string              `yaml:"name,omitempty" json:"name,omitempty"`
	Description     string              `yaml:"description,omitempty" json:"description,omitempty"`
	Extends         string              `yaml:"extends,omitempty" json:"extends,omitempty"`
	MergeStrategy   MergeStrategy       `yaml:"merge_strategy,omitempty" json:"merge_strategy,omitempty"`
	Rules           *Rules              `yaml:"rules,omitempty" json:"rules,omitempty"`
	Extensions      *Extensions         `yaml:"extensions,omitempty" json:"extensions,omitempty"`
	Metadata        *GovernanceMetadata `yaml:"metadata,omitempty" json:"metadata,omitempty"`
}

type Rules struct {
	ForbiddenPaths        *ForbiddenPathsRule        `yaml:"forbidden_paths,omitempty" json:"forbidden_paths,omitempty"`
	PathAllowlist         *PathAllowlistRule         `yaml:"path_allowlist,omitempty" json:"path_allowlist,omitempty"`
	Egress                *EgressRule                `yaml:"egress,omitempty" json:"egress,omitempty"`
	SecretPatterns        *SecretPatternsRule        `yaml:"secret_patterns,omitempty" json:"secret_patterns,omitempty"`
	PatchIntegrity        *PatchIntegrityRule        `yaml:"patch_integrity,omitempty" json:"patch_integrity,omitempty"`
	ShellCommands         *ShellCommandsRule         `yaml:"shell_commands,omitempty" json:"shell_commands,omitempty"`
	ToolAccess            *ToolAccessRule            `yaml:"tool_access,omitempty" json:"tool_access,omitempty"`
	ComputerUse           *ComputerUseRule           `yaml:"computer_use,omitempty" json:"computer_use,omitempty"`
	RemoteDesktopChannels *RemoteDesktopChannelsRule `yaml:"remote_desktop_channels,omitempty" json:"remote_desktop_channels,omitempty"`
	InputInjection        *InputInjectionRule        `yaml:"input_injection,omitempty" json:"input_injection,omitempty"`
}

type ForbiddenPathsRule struct {
	Enabled    bool     `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Patterns   []string `yaml:"patterns,omitempty" json:"patterns,omitempty"`
	Exceptions []string `yaml:"exceptions,omitempty" json:"exceptions,omitempty"`
}

type PathAllowlistRule struct {
	Enabled bool     `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Read    []string `yaml:"read,omitempty" json:"read,omitempty"`
	Write   []string `yaml:"write,omitempty" json:"write,omitempty"`
	Patch   []string `yaml:"patch,omitempty" json:"patch,omitempty"`
}

type EgressRule struct {
	Enabled bool          `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Allow   []string      `yaml:"allow,omitempty" json:"allow,omitempty"`
	Block   []string      `yaml:"block,omitempty" json:"block,omitempty"`
	Default DefaultAction `yaml:"default,omitempty" json:"default,omitempty"`
}

type SecretPattern struct {
	Name        string   `yaml:"name" json:"name"`
	Pattern     string   `yaml:"pattern" json:"pattern"`
	Severity    Severity `yaml:"severity" json:"severity"`
	Description string   `yaml:"description,omitempty" json:"description,omitempty"`
}

type SecretPatternsRule struct {
	Enabled   bool            `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Patterns  []SecretPattern `yaml:"patterns,omitempty" json:"patterns,omitempty"`
	SkipPaths []string        `yaml:"skip_paths,omitempty" json:"skip_paths,omitempty"`
}

type PatchIntegrityRule struct {
	Enabled           bool     `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	MaxAdditions      int      `yaml:"max_additions,omitempty" json:"max_additions,omitempty"`
	MaxDeletions      int      `yaml:"max_deletions,omitempty" json:"max_deletions,omitempty"`
	ForbiddenPatterns []string `yaml:"forbidden_patterns,omitempty" json:"forbidden_patterns,omitempty"`
	RequireBalance    bool     `yaml:"require_balance,omitempty" json:"require_balance,omitempty"`
	MaxImbalanceRatio *float64 `yaml:"max_imbalance_ratio,omitempty" json:"max_imbalance_ratio,omitempty"`
}

type ShellCommandsRule struct {
	Enabled           bool     `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	ForbiddenPatterns []string `yaml:"forbidden_patterns,omitempty" json:"forbidden_patterns,omitempty"`
}

type ToolAccessRule struct {
	Enabled             bool          `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Allow               []string      `yaml:"allow,omitempty" json:"allow,omitempty"`
	Block               []string      `yaml:"block,omitempty" json:"block,omitempty"`
	RequireConfirmation []string      `yaml:"require_confirmation,omitempty" json:"require_confirmation,omitempty"`
	Default             DefaultAction `yaml:"default,omitempty" json:"default,omitempty"`
	MaxArgsSize         *int          `yaml:"max_args_size,omitempty" json:"max_args_size,omitempty"`
}

type ComputerUseRule struct {
	Enabled        bool            `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Mode           ComputerUseMode `yaml:"mode,omitempty" json:"mode,omitempty"`
	AllowedActions []string        `yaml:"allowed_actions,omitempty" json:"allowed_actions,omitempty"`
}

type RemoteDesktopChannelsRule struct {
	Enabled      bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Clipboard    bool `yaml:"clipboard,omitempty" json:"clipboard,omitempty"`
	FileTransfer bool `yaml:"file_transfer,omitempty" json:"file_transfer,omitempty"`
	Audio        bool `yaml:"audio,omitempty" json:"audio,omitempty"`
	DriveMapping bool `yaml:"drive_mapping,omitempty" json:"drive_mapping,omitempty"`
}

type InputInjectionRule struct {
	Enabled                   bool     `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	AllowedTypes              []string `yaml:"allowed_types,omitempty" json:"allowed_types,omitempty"`
	RequirePostconditionProbe bool     `yaml:"require_postcondition_probe,omitempty" json:"require_postcondition_probe,omitempty"`
}

type Extensions struct {
	Posture   *PostureExtension   `yaml:"posture,omitempty" json:"posture,omitempty"`
	Origins   *OriginsExtension   `yaml:"origins,omitempty" json:"origins,omitempty"`
	Detection *DetectionExtension `yaml:"detection,omitempty" json:"detection,omitempty"`
}

type PostureExtension struct {
	Initial     string                  `yaml:"initial" json:"initial"`
	States      map[string]PostureState `yaml:"states,omitempty" json:"states,omitempty"`
	Transitions []PostureTransition     `yaml:"transitions,omitempty" json:"transitions,omitempty"`
}

type PostureState struct {
	Description  string         `yaml:"description,omitempty" json:"description,omitempty"`
	Capabilities []string       `yaml:"capabilities,omitempty" json:"capabilities,omitempty"`
	Budgets      map[string]int `yaml:"budgets,omitempty" json:"budgets,omitempty"`
}

type PostureTransition struct {
	From  string            `yaml:"from" json:"from"`
	To    string            `yaml:"to" json:"to"`
	On    TransitionTrigger `yaml:"on" json:"on"`
	After *string           `yaml:"after,omitempty" json:"after,omitempty"`
}

type OriginsExtension struct {
	DefaultBehavior *OriginDefaultBehavior `yaml:"default_behavior,omitempty" json:"default_behavior,omitempty"`
	Profiles        []OriginProfile        `yaml:"profiles,omitempty" json:"profiles,omitempty"`
}

type OriginProfile struct {
	ID          string            `yaml:"id" json:"id"`
	Match       *OriginMatch      `yaml:"match,omitempty" json:"match,omitempty"`
	Posture     *string           `yaml:"posture,omitempty" json:"posture,omitempty"`
	ToolAccess  *ToolAccessRule   `yaml:"tool_access,omitempty" json:"tool_access,omitempty"`
	Egress      *EgressRule       `yaml:"egress,omitempty" json:"egress,omitempty"`
	Data        *OriginDataPolicy `yaml:"data,omitempty" json:"data,omitempty"`
	Budgets     *OriginBudgets    `yaml:"budgets,omitempty" json:"budgets,omitempty"`
	Bridge      *BridgePolicy     `yaml:"bridge,omitempty" json:"bridge,omitempty"`
	Explanation *string           `yaml:"explanation,omitempty" json:"explanation,omitempty"`
}

type OriginMatch struct {
	Provider             string   `yaml:"provider,omitempty" json:"provider,omitempty"`
	TenantID             string   `yaml:"tenant_id,omitempty" json:"tenant_id,omitempty"`
	SpaceID              string   `yaml:"space_id,omitempty" json:"space_id,omitempty"`
	SpaceType            string   `yaml:"space_type,omitempty" json:"space_type,omitempty"`
	Visibility           string   `yaml:"visibility,omitempty" json:"visibility,omitempty"`
	ExternalParticipants *bool    `yaml:"external_participants,omitempty" json:"external_participants,omitempty"`
	Tags                 []string `yaml:"tags,omitempty" json:"tags,omitempty"`
	Sensitivity          string   `yaml:"sensitivity,omitempty" json:"sensitivity,omitempty"`
	ActorRole            string   `yaml:"actor_role,omitempty" json:"actor_role,omitempty"`
}

type OriginDataPolicy struct {
	AllowExternalSharing  *bool `yaml:"allow_external_sharing,omitempty" json:"allow_external_sharing,omitempty"`
	RedactBeforeSend      *bool `yaml:"redact_before_send,omitempty" json:"redact_before_send,omitempty"`
	BlockSensitiveOutputs *bool `yaml:"block_sensitive_outputs,omitempty" json:"block_sensitive_outputs,omitempty"`
}

type OriginBudgets struct {
	ToolCalls     *int `yaml:"tool_calls,omitempty" json:"tool_calls,omitempty"`
	EgressCalls   *int `yaml:"egress_calls,omitempty" json:"egress_calls,omitempty"`
	ShellCommands *int `yaml:"shell_commands,omitempty" json:"shell_commands,omitempty"`
}

type BridgePolicy struct {
	AllowCrossOrigin *bool          `yaml:"allow_cross_origin,omitempty" json:"allow_cross_origin,omitempty"`
	AllowedTargets   []BridgeTarget `yaml:"allowed_targets,omitempty" json:"allowed_targets,omitempty"`
	RequireApproval  *bool          `yaml:"require_approval,omitempty" json:"require_approval,omitempty"`
}

type BridgeTarget struct {
	Provider   string   `yaml:"provider,omitempty" json:"provider,omitempty"`
	SpaceType  string   `yaml:"space_type,omitempty" json:"space_type,omitempty"`
	Tags       []string `yaml:"tags,omitempty" json:"tags,omitempty"`
	Visibility string   `yaml:"visibility,omitempty" json:"visibility,omitempty"`
}

type DetectionExtension struct {
	PromptInjection *PromptInjectionDetection `yaml:"prompt_injection,omitempty" json:"prompt_injection,omitempty"`
	Jailbreak       *JailbreakDetection       `yaml:"jailbreak,omitempty" json:"jailbreak,omitempty"`
	ThreatIntel     *ThreatIntelDetection     `yaml:"threat_intel,omitempty" json:"threat_intel,omitempty"`
}

type PromptInjectionDetection struct {
	Enabled        *bool           `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	WarnAtOrAbove  *DetectionLevel `yaml:"warn_at_or_above,omitempty" json:"warn_at_or_above,omitempty"`
	BlockAtOrAbove *DetectionLevel `yaml:"block_at_or_above,omitempty" json:"block_at_or_above,omitempty"`
	MaxScanBytes   *int            `yaml:"max_scan_bytes,omitempty" json:"max_scan_bytes,omitempty"`
}

type JailbreakDetection struct {
	Enabled        *bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	BlockThreshold *int  `yaml:"block_threshold,omitempty" json:"block_threshold,omitempty"`
	WarnThreshold  *int  `yaml:"warn_threshold,omitempty" json:"warn_threshold,omitempty"`
	MaxInputBytes  *int  `yaml:"max_input_bytes,omitempty" json:"max_input_bytes,omitempty"`
}

type ThreatIntelDetection struct {
	Enabled             *bool    `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	PatternDB           *string  `yaml:"pattern_db,omitempty" json:"pattern_db,omitempty"`
	SimilarityThreshold *float64 `yaml:"similarity_threshold,omitempty" json:"similarity_threshold,omitempty"`
	TopK                *int     `yaml:"top_k,omitempty" json:"top_k,omitempty"`
}

type GovernanceMetadata struct {
	Author         string         `yaml:"author,omitempty" json:"author,omitempty"`
	ApprovedBy     string         `yaml:"approved_by,omitempty" json:"approved_by,omitempty"`
	ApprovalDate   string         `yaml:"approval_date,omitempty" json:"approval_date,omitempty"`
	Classification Classification `yaml:"classification,omitempty" json:"classification,omitempty"`
	ChangeTicket   string         `yaml:"change_ticket,omitempty" json:"change_ticket,omitempty"`
	LifecycleState LifecycleState `yaml:"lifecycle_state,omitempty" json:"lifecycle_state,omitempty"`
	PolicyVersion  *int           `yaml:"policy_version,omitempty" json:"policy_version,omitempty"`
	EffectiveDate  string         `yaml:"effective_date,omitempty" json:"effective_date,omitempty"`
	ExpiryDate     string         `yaml:"expiry_date,omitempty" json:"expiry_date,omitempty"`
}
